### ISSUE TITLE
Python API/CLI does not include precmz or SMILES/compound name in results_df

### ISSUE THREAD

**Issue by j-a-dietrich** [mwang87/MassQueryLanguage#244]
Hey, I was wondering why the results_df from the Python API does not include precursor masses or SMILES like in the sandbox, even though they are defined in the .mgf file. I tested it with a GNPS library dataset as well as with an in-house dataset and followed the documentation for running a query. The query works fine.

**Comment by mwang87** [comment]
the  sandbox does extra enrichment that the basic querying infrastructure does not.
